# Generated by Django 5.0.2 on 2024-03-04 18:46

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.models.MyAccountManager()),
            ],
        ),
    ]
